version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: gunicorn --bind 0.0.0.0:8000 --workers 1 --access-logfile - --log-level debug app.app:app
    environment:
      - FLASK_ENV=production