version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=8000 --debug
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.app:app
