"""Add poll field for expiration datetime

Revision ID: 0e932ca015e3
Revises: 550dac70d51f
Create Date: 2026-03-22 15:34:40.382319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e932ca015e3'
down_revision = '550dac70d51f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poll_expires', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.drop_column('poll_expires')

    # ### end Alembic commands ###
