"""v1.5 upgrade

Revision ID: 1afde95bb778
Revises: 3e163497f885
Create Date: 2025-12-31 14:22:13.547515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1afde95bb778'
down_revision = '3e163497f885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfa_active', sa.Boolean(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('totp_active', sa.Boolean(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('activated', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('activated')
        batch_op.drop_column('totp_active')
        batch_op.drop_column('totp_secret')
        batch_op.drop_column('mfa_active')

    op.drop_table('recovery_codes')
    # ### end Alembic commands ###
