"""immutability

Revision ID: 303481549251
Revises: 4396405aba8b
Create Date: 2026-03-24 18:02:08.563766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303481549251'
down_revision = '4396405aba8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('immutable_question', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll_questions', schema=None) as batch_op:
        batch_op.drop_column('immutable_question')

    # ### end Alembic commands ###
