"""private vote

Revision ID: 4396405aba8b
Revises: 0e932ca015e3
Create Date: 2026-03-23 20:49:23.386313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4396405aba8b'
down_revision = '0e932ca015e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private_vote', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll_questions', schema=None) as batch_op:
        batch_op.drop_column('private_vote')

    # ### end Alembic commands ###
