"""Added voter_id column to PollVoter

Revision ID: 9707706692be
Revises: 2ba18391895d
Create Date: 2026-01-26 12:48:55.560407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9707706692be'
down_revision = '2ba18391895d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll_voters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'poll_options', ['option_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll_voters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('option_id')

    # ### end Alembic commands ###
