"""Migrate schema for v1.5

Revision ID: e351e2e74eb6
Revises: 
Create Date: 2025-12-27 23:23:48.656463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e351e2e74eb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfa_active', sa.Boolean(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('totp_active', sa.Boolean(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('activated', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('activated')
        batch_op.drop_column('totp_active')
        batch_op.drop_column('totp_secret')
        batch_op.drop_column('mfa_active')

    # ### end Alembic commands ###
